CREATE TABLE IF NOT EXISTS dishes(
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
price NUMERIC(6,2),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);