CREATE TABLE IF NOT EXISTS orders(
id SERIAL PRIMARY KEY,
users_id INTEGER NOT NULL,
price NUMERIC(6,2) NOT NULL,
payment_status BOOLEAN NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);