version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    ports:
      - 5002:5002
    volumes:
      - .:/restaurant
    env_file: .env
    depends_on:
      - database
    container_name: restaurant-api
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'

  database:
    build: 
      context: .
      dockerfile: ./docker/db.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: restaurant
    container_name: restaurant-db
    ports:
      - 33067:3306
    volumes:
      - restaurant-data:/var/lib/mysql 

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 5003:80
    environment:
      - 'PMA_HOST=database'
      - 'PMA_PORT=3306'
    container_name: restaurant-pma


# persisted storage
volumes:
  restaurant-data: